server:
    port: 8080
    address: 127.0.0.1
    context-path: /
    swoole:
        reactor_num: 2
        worker_num: 4
        backlog: 128
        max_request: 50
        dispatch_mode: 1
winter:
    application:
        name: My Demo Application
        id: MyApp
        version: 1.0.0-DEV
    namespaces:
        cacheTime: 10
    route:
        cacheTime: 10
    task:
        async:
            poolSize: 1
            queueCapacity: 50
            argsSize: 2048
        scheduling:
            poolSize: 1
            queueCapacity: 50
myApp:
    value1: This is string
    value2: 99
    value3: true
    value4: 10.89

datasource:
    -   name: default
        url: "sqlite::memory:"
        username:
        password:
        validationQuery: SELECT 'Databse Connected'
        driverClass: dev\winterframework\pdbc\pdo\PdoDataSource
        connection:
            persistent: true
            errorMode: ERRMODE_EXCEPTION
            columnsCase: CASE_NATURAL
            connectionTimeoutSecs: 30
            autoCommit: true
            defaultrowprefetch: 100

modules:

management:
    endpoints:
        enabled: true
    endpoint:
        beans:
            enabled: true,
            path: "acme/beans"
        configprops:
            enabled: true,
            path: "acme/configprops"
        env:
            enabled: true,
            path: "acme/env"
        health:
            enabled: true,
            path: "acme/health"
        info:
            enabled: true,
            path: "acme/info"
        mappings:
            enabled: true,
            path: "acme/mappings"
